on:
  pull_request:
    branches:
      - Release
  push:
    branches:
      - Release
env:
  app_ver: v1.1.9
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.10'
      - run: flutter pub get
      - run: |
         flutter build apk --release
         mv ./build/app/outputs/apk/release/app-release.apk ./Colorful_Notes_$app_ver.apk
         flutter build apk --release --split-per-abi
         mv ./build/app/outputs/apk/release/app-arm64-v8a-release.apk ./build/app/outputs/apk/release/Colorful_Notes_$app_ver-arm64-v8a.apk
         mv ./build/app/outputs/apk/release/app-armeabi-v7a-release.apk ./build/app/outputs/apk/release/Colorful_Notes_$app_ver-armeabi-v7a.apk
         mv ./build/app/outputs/apk/release/app-x86_64-release.apk ./build/app/outputs/apk/release/Colorful_Notes_$app_ver-x86_64.apk
         mv ./Colorful_Notes_$app_ver.apk ./build/app/outputs/apk/release/Colorful_Notes_$app_ver.apk
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: ${{ env.app_ver }}
          token: ${{ secrets.TOKEN }}