on:
  pull_request:
    branches:
      - Release
  push:
    branches:
      - Release
env:
  app_ver: v1.1.3
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.10'
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - name: Rename Packages
        run:  |
         mv ./build/app/outputs/apk/debug/app-arm64-v8a-debug.apk ./build/app/outputs/apk/debug/Colorful_Notes_$app_ver-arm64-v8a.apk
         mv ./build/app/outputs/apk/debug/app-armeabi-v7a-debug.apk ./build/app/outputs/apk/debug/Colorful_Notes_$app_ver-armeabi-v7a.apk
         mv ./build/app/outputs/apk/debug/app-x86_64-debug.apk ./build/app/outputs/apk/debug/Colorful_Notes_$app_ver-x86_64.apk
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: $app_ver
          token: ${{ secrets.TOKEN }}